CREATE TABLE MENU (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(20) NOT NULL,
    price INT NOT NULL
);

CREATE TABLE MEMBERS (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE POINTS (
    member_id BIGINT NOT NULL PRIMARY KEY,
    point INT NOT NULL DEFAULT 0,

    FOREIGN KEY (member_id) REFERENCES MEMBERS (id)
);

CREATE TABLE ORDERS (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    member_id BIGINT NOT NULL,
    dates DATE NOT NULL,
    menu_id BIGINT NOT NULL,
    price INT NOT NULL,

    FOREIGN KEY (member_id) REFERENCES MEMBERS (id),
    FOREIGN KEY (menu_id) REFERENCES MEMBERS (id)
);

CREATE TABLE BEST_MENU (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    dates DATE NOT NULL,
    menu_id BIGINT NOT NULL,
    name VARCHAR(20) NOT NULL,
    price INT NOT NULL,
    order_count INT NOT NULL
);
